### PR TITLE
Proofreading documentation

### PR DESCRIPTION
**Pull request by YaxelPerez**
This PR corrects typos and fixes grammatical errors.

### CODE REVIEW

**Comment by kfogel** [comment]
@YaxelPerez, this change looks really good -- nice & careful job.

I have one request before it gets merged: please undo the aspect of the change in which two spaces after a sentence-ending period gets changed to one space.  I realize that this is a matter of some controversy on the Internet, and that the one-spacers are adamant that their way is the One True Way :-).  (I won't cite any sources here, but advocates of both sides are easily findable with a web search.)

While most of the controversy is about aesthetics -- despite scientifically dubious claims about readability on both sides -- there is actually one objective fact that is relevant here:

When there are two spaces after each sentence-ending period in a source document (such as a Markdown file), then text editing software (such as Vim or Emacs) can offer the user sentence-wise motion commands.

Thus with one keystroke, one can navigate forward by a sentence or backward by a sentence.  This is very useful, and it's why you see two-spaces in OTS documents.  When there is only one space, then the end of a sentence cannot be programmatically distinguished from an abbreviation like "St. Anastasia" or "Dr. Who", and that breaks sentence-wise navigation.

How the text gets *rendered* is another matter entirely; I have no strong opinion there, and it doesn't affect us anyway.  The question for us is just about how to format the source document that humans actually have to edit.

**Comment by kfogel** [comment]
+1 to @frankduncan's comments about the commit message.

https://chris.beams.io/posts/git-commit/ is still the go-to reference on this

**Comment by YaxelPerez** [comment]
I accidentally force pushed to master :facepalm:. Fixed this, and rolled back the double-space edit.

**Comment by kfogel** [comment]
Hey, @YaxelPerez.  I see some activity here, but no responses to what @frankduncan wrote or what I wrote.  Our comments are from 10 days ago.  Please prioritize communication -- I can't (easily) know what's going on unless you tell me :-).

**Comment by frankduncan** [comment]
@kfogel He actually wrote a comment that I received an email on, but weirdly it's deleted from here and when I click the "view on github" link it just takes me to here.  https://github.com/OpenTechStrategies/torque/pull/29#issuecomment-625039143

**Pull request merged**
